feat: Snowflake Compare
discordjs/discord-toolkit-bot pull request #9
Opened 2022-10-16 05:17 UTC by twisttaan

2022-10-16 16:07 UTC, almostSouji commented
How exactly is this useful for support?

2022-10-17 00:24 UTC, JPBM135 requested changes
This still has a good question if it is useful for support at all

2022-10-17 00:24 UTC, JPBM135 commented on src/commands/snowflake.ts
> +				console.log(args);
Use `logger.warn` here

2022-10-17 00:24 UTC, JPBM135 commented on src/commands/sub/snowflake/compare.ts
> +	const snowflake2 = SnowflakeUtil.deconstruct(args.snowflake2);
Why not reference the timestamp directly here and pass only the variable to the arguments:
- Timestamp is already a number, using deconstruction or the timestamp utility, no need for conversion

```suggestion
	const snowflake1 = SnowflakeUtil.timestampFrom(args.snowflake1);
	const snowflake2 = SnowflakeUtil.timestampFrom(args.snowflake2);
```

2022-10-17 00:24 UTC, JPBM135 commented on src/commands/sub/snowflake/compare.ts
> +			new Date(Number(snowflake1.timestamp)).getTime() - new Date(Number(snowflake2.timestamp)).getTime()
```suggestion
			snowflake1.timestamp - snowflake2.timestamp
```

Why not compare the timestamps themselves instead of creating a Date?

2022-10-27 03:20 UTC, twisttaan commented
This has no use and support, and is only really useful for comparing "snails"; a fad when 2 or more people respond to someone else with the same general concept.

2022-10-27 03:20 UTC, closed without merging